### PR TITLE
Slight optimization, version increment

### PR DESCRIPTION
**Pull request by gappleto97**
Whether or not this is merged, could you kindly update the version on pypi? I'd like to mark this as a dependency, but I need the integer encoding to do so, and that's not yet on pypi.

### CODE REVIEW

**Comment by keis** [comment]
Oh right, will do

There's a odd merge commit in the set could you rebase this to avoid that?

**Comment by gappleto97** [comment]
Sure. I'll get that come lunch tomorrow.

**Comment by gappleto97** [comment]
Rebased and squashed for you.

**Comment by keis** [comment]
Thanks! new version on pypi

**Pull request merged**
