### PR TITLE
added reverse and leading_z identity tests

### PR DESCRIPTION
**Pull request by fametrano**

### CODE REVIEW

**Comment by keis** [comment]
Hey, thanks for the PR

I'm not not sure if you're saying the checksum error is a bug in implementation or if it's a copy paste error

**Comment by fametrano** [comment]
checksum error? I didn't say anything about checksum error, I only added 3 new tests here

**Comment by keis** [comment]
yes. but they are failing.

**Comment by fametrano** [comment]
Sorry I am not able to run the tests locally, will have to learn how to do it. Anyway, the test failure is "no environment variable set", so I am puzzled... how it can be related with this proposed change?

**Comment by keis** [comment]
the one I'm looking at in travis is

'''
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/keis/base58/test.py", line 69, in test_check_reverse_identity
    out = b58encode_check(b58decode_check(data))
  File "/home/travis/build/keis/base58/base58.py", line 108, in b58decode_check
    raise ValueError("Invalid checksum")
ValueError: Invalid checksum
'''

how are you running the tests?

**Pull request closed without merging**
