### PR TITLE
New alias for XRP alphabet

### PR DESCRIPTION
**Pull request by alloyxrp**
Add alias to use `XRP_ALPHABET` instead of `RIPPLE_ALPHABET` , since the token name is XRP.

### CODE REVIEW

**Comment by gappleto97** [comment]
There is not a similar alias for BTC. Do you want this because it is used in other libraries, or just to make lines shorter?

**Comment by alloyxrp** [comment]
> There is not a similar alias for BTC. Do you want this because it is used in other libraries, or just to make lines shorter?

Actually, it's a bit of both. The token is called XRP (Not Ripple). I understand that the term Ripple is still in use. But newer libraries are encouraged to use the term _XRP_ instead for accurate representation.
For the foreseeable future, it would remain as an alias, so that things don't break.

**Comment by ntninja** [comment]
Code suggestion: This should instead use `XRP_ALPHABET = RIPPLE_ALPHABET` to avoid duplicating the string in memory.

**Comment by alloyxrp** [comment]
> Code suggestion: This should instead use `XRP_ALPHABET = RIPPLE_ALPHABET` to avoid duplicating the string in memory.

Thanks! An very obvious mistake on my part. Corrected.

**Comment by keis** [comment]
Thanks for the PR. I know very little about ripple but if XRP is indeed the favoured term it makes sense to use it here.

Do you have a link to some ripple docs that explains the difference?
Can you also update the examples in the README and tests to use the XRP constant instead?

**Comment by alloyxrp** [comment]
> Thanks for the PR. I know very little about ripple but if XRP is indeed the favoured term it makes sense to use it here.
> 
> Do you have a link to some ripple docs that explains the difference?
> Can you also update the examples in the README and tests to use the XRP constant instead?

Sure. While it is sometimes called Ripple (mistakenly), the correct term for the token is XRP - https://xrpl.org/base58-encodings.html
I'll update the readme and examples too.

**Pull request merged**
